CON_TIMEOUT: 1 # in seconds, time between connection attempts
WAIT_TIMEOUT: 1 # in seconds, time between armable checks
START_ALTITUDE: 1.5 # in meters
FLY_ALTITUDE: 1.5  # in meters
FLY_SPEED: 5 # in meters/second
MEANDER_WIDTH: 14 #in meters
MEANDER_LENGTH: 5 #in meters
MEANDER_COUNT: 5
SEARCH_ANGLE: 30 #in degrees

