CON_TIMEOUT: 1 # in seconds, time between connection attempts
WAIT_TIMEOUT: 1 # in seconds, time between armable checks
MEANDER_MIN_TIMEOUT: 4 # in seconds, min time for meander
MEANDER_MIN_SPEED: 0.5 # in sec, if drone gets slow than this, next meander starts
MEANDER_MIN_SPEED_TIMEOUT: 1 #time between checks if drone slowed down enough
START_ALTITUDE: 1 # in meters
FLY_ALTITUDE: 1  # in meters
FLY_SPEED: 3 # in meters/second
MEANDER_WIDTH: 4 #in meters
MEANDER_LENGTH: 4 #in meters
MEANDER_COUNT: 4
SEARCH_ANGLE: 30 #in degrees

