CON_TIMEOUT: 15 # in seconds, time between connection attempts
WAIT_TIMEOUT: 5 # in seconds, time between armable checks
START_ALTITUDE: 2 # in meters
FLY_ALTITUDE: 2  # in meters
FLY_SPEED: 3 # in meters/second
MEANDER_WIDTH: 5 #in meters
MEANDER_LENGTH: 2 #in meters
MEANDER_COUNT: 4
SEARCH_ANGLE: 30 #in degrees

