CON_TIMEOUT: 1 # in seconds, time between connection attempts
WAIT_TIMEOUT: 1 # in seconds, time between armable checks
START_ALTITUDE: 1 # in meters
FLY_ALTITUDE: 1  # in meters
FLY_SPEED: 3 # in meters/second
MEANDER_WIDTH: 18 #in meters
MEANDER_LENGTH: 7 #in meters
MEANDER_COUNT: 6
SEARCH_ANGLE: 30 #in degrees

